[web]
gs-web ansible_host=133.125.90.129 ansible_port=26622

[batch]
gs-batch ansible_host=192.168.0.20 ansible_port=22 ansible_ssh_common_args='-o ProxyJump=gsuser@133.125.90.129:26622'

[all:vars]
ansible_user=gsuser
ansible_ssh_private_key_file=~/.ssh/202602_sakura_key
