---
- name: Apply geo blocking to VirtualHosts
  template:
    src: "{{ item }}.conf.j2"
    dest: "/etc/nginx/conf.d/{{ item }}.conf"
    owner: root
    group: root
    mode: '0644'
    backup: yes
  become: true
  loop:
    - supplier2
    - portal2
    - portal2-new
  notify: reload nginx

- name: Verify all VirtualHost configurations
  shell: nginx -t
  become: true
  changed_when: false
